### ISSUE TITLE
Android build error with cordova plugin camera after installing cordova plugin androidx adapter

### ISSUE THREAD

**Issue by yuanzuo** [dpa99c/cordova-plugin-firebasex#69]
hello. I followed the steps in issue #29 and #41 but I still got android build error. Please help!

>cordova -v
8.0.0

>cordova platform ls
Installed platforms:
  android 8.0.0

>cordova plugin ls
com.cmackay.plugins.googleanalytics 0.1.22 "GoogleAnalytics"
com.phonegap.plugins.fileopener 1.0.0 "File Opener"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-cocoapod-supportx 1.7.3 "Cordova CocoaPods Dependency Support"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-contacts 2.0.1 "Contacts"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-firebasex 3.0.1 "Google Firebase Plugin"
cordova-plugin-geolocation 2.4.0 "Geolocation"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-network-information 1.2.0 "Network Information"
cordova-plugin-splashscreen 3.1.0 "Splashscreen"
cordova-plugin-statusbar 2.1.2 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
org.apache.cordova.file 1.3.3 "File"
org.apache.cordova.file-transfer 0.5.0 "File Transfer"

\platforms\android\app\src\main\java\org\apache\cordova\camera\CameraLauncher.java
error: cannot find symbol method getUriForFile(Activity,String,File)

error: package android.support.v4.content does not exist

\platforms\android\app\src\main\java\org\apache\cordova\camera\FileProvider.java

error: package android.support.v4.content does not exist

**Comment by fpajor** [comment]
You need cordova 9.0.0: https://cordova.apache.org/announcements/2019/03/22/cordova-cli-release-9.0.0.html
After installing it remove the android platform and add it again.

**Comment by yuanzuo** [comment]
the requirement for androidx adapter plugin is cordova 8.0 and android 8.0.
I don't understand why I need cordova 9.0

**Comment by fpajor** [comment]
https://github.com/dpa99c/cordova-plugin-firebasex#supported-cordova-versions

**Comment by yuanzuo** [comment]
I still got same error after upgrading cordova to 9.0.0. Android platform version is 8.0.0

>cordova plugin ls
com.cmackay.plugins.googleanalytics 0.1.22 "GoogleAnalytics"
com.phonegap.plugins.fileopener 1.0.0 "File Opener"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-cocoapod-supportx 1.7.3 "Cordova CocoaPods Dependency Support"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-contacts 2.0.1 "Contacts"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-firebasex 3.0.1 "Google Firebase Plugin"
cordova-plugin-geolocation 2.4.0 "Geolocation"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-network-information 1.2.0 "Network Information"
cordova-plugin-splashscreen 3.1.0 "Splashscreen"
cordova-plugin-statusbar 2.1.2 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
org.apache.cordova.file 1.3.3 "File"
org.apache.cordova.file-transfer 0.5.0 "File Transfer"


if I set android.useAndroidX and android.enableJetifier to TRUE in gradle.properties, I got CameraLauncher.java file error: 

\platforms\android\app\src\main\java\org\apache\cordova\camera\CameraLauncher.java
error: cannot find symbol method getUriForFile(Activity,String,File)


If I remove android.useAndroidX and android.enableJetifier settings from in gradle.properties, I got Android issues: 

Error: Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

now I am stuck here. Can someone help?

**Comment by dpa99c** [comment]
Please update to the latest versions of `cordova-plugin-firebasex`:

    cordova plugin rm cordova-plugin-firebasex && cordova plugin add cordova-plugin-firebasex@latest

Then re-add the Android platform:

    cordova platform rm android && cordova platform add android@latest

Also see https://github.com/apache/cordova-plugin-camera/issues/480

**Comment by yuanzuo** [comment]
It works for me now. Thanks Dave!

**Comment by fpachecoibz** [comment]
Hi!
I can't build cordova project with cordova-camera and firebasex. I already have the latest cordova (9.0.0), cordova-android (8.0.0), firebasex (8.0.1), androidx (1.0.2) and androidx-adapter (1.1.0)

Only happens when I add the following in config.xml:

<config-file target="AndroidManifest.xml" parent="/manifest/application">
      <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon"/>
    </config-file>

If I remove it, then the build is OK. but i need to set another default icon instead app icon.

The error is:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  /home/fpacheco/Proyectos/apppaciente/platforms/android/app/src/main/res/xml/config.xml:106: error: unbound prefix.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
/home/fpacheco/Proyectos/apppaciente/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  /home/fpacheco/Proyectos/apppaciente/platforms/android/app/src/main/res/xml/config.xml:106: error: unbound prefix.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

and the content of /app/src/main/res/xml/config.xml is:

```
<?xml version='1.0' encoding='utf-8'?>
<widget android-versionCode="100200" date="21/07/2016" environment="PRO" id="com.xxxx.apppacientes" version="1.0.20" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0" xmlns:rim="http://www.blackberry.com/ns/widgets">
    <feature name="Device">
        <param name="android-package" value="org.apache.cordova.device.Device" />
    </feature>
    <feature name="Notification">
        <param name="android-package" value="org.apache.cordova.dialogs.Notification" />
    </feature>
    <feature name="NetworkStatus">
        <param name="android-package" value="org.apache.cordova.networkinformation.NetworkManager" />
    </feature>
    <feature name="SplashScreen">
        <param name="android-package" value="org.apache.cordova.splashscreen.SplashScreen" />
        <param name="onload" value="true" />
    </feature>
    <feature name="Whitelist">
        <param name="android-package" value="org.apache.cordova.whitelist.WhitelistPlugin" />
        <param name="onload" value="true" />
    </feature>
    <feature name="StatusBar">
        <param name="android-package" value="org.apache.cordova.statusbar.StatusBar" />
        <param name="onload" value="true" />
    </feature>
    <feature name="Keyboard">
        <param name="android-package" value="io.ionic.keyboard.IonicKeyboard" />
        <param name="onload" value="true" />
    </feature>
    <feature name="InAppBrowser">
        <param name="android-package" value="org.apache.cordova.inappbrowser.InAppBrowser" />
    </feature>
    <feature name="AppAvailability">
        <param name="android-package" value="com.ohh2ahh.appavailability.AppAvailability" />
    </feature>
    <feature name="File">
        <param name="android-package" value="org.apache.cordova.file.FileUtils" />
        <param name="onload" value="true" />
    </feature>
    <allow-navigation href="cdvfile:*" />
    <feature name="FileTransfer">
        <param name="android-package" value="org.apache.cordova.filetransfer.FileTransfer" />
    </feature>
    <feature name="FileOpener2">
        <param name="android-package" value="io.github.pwlin.cordova.plugins.fileopener2.FileOpener2" />
    </feature>
    <feature name="Geolocation">
        <param name="android-package" value="org.apache.cordova.geolocation.Geolocation" />
    </feature>
    <feature name="Permissions">
        <param name="android-package" value="com.android.plugins.Permissions" />
    </feature>
    <feature name="Globalization">
        <param name="android-package" value="org.apache.cordova.globalization.Globalization" />
    </feature>
    <feature name="CordovaPluginsCleartext">
        <param name="android-package" value="cordova.plugins.cleartext" />
    </feature>
    <feature name="FirebasePlugin">
        <param name="android-package" value="org.apache.cordova.firebase.FirebasePlugin" />
        <param name="onload" value="true" />
    </feature>
    <feature name="Camera">
        <param name="android-package" value="org.apache.cordova.camera.CameraLauncher" />
    </feature>
    <name>xxx</name>
    <description>xxx</description>
    <author email="cem@atsistemas.com" href="http://www.atsistemas.com">atSistemas S.A.</author>
    <access origin="*" />
    <content src="index.html" />
    <rim:permissions>
    </rim:permissions>
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <allow-navigation href="http://*/*" />
    <allow-navigation href="https://*/*" />
    <hook src="hooks/android/customizeTheme.js" type="after_platform_add" />
    <hook src="hooks/android/customizeColors.js" type="after_platform_add" />
    <allow-intent href="market:*" />
    <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
    <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
    <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
    <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
    <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
    <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
    <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
    <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
    <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
    <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
    <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
    <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
    <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
    <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
    <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
    <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
    <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
    <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
    <resource-file src="resources/android/notification-icon/mdpi-notification-icon.png" target="app/src/main/res/drawable-mdpi/notification_icon.png" />
    <resource-file src="resources/android/notification-icon/hdpi-notification-icon.png" target="app/src/main/res/drawable-hdpi/notification_icon.png" />
    <resource-file src="resources/android/notification-icon/xhdpi-notification-icon.png" target="app/src/main/res/drawable-xhdpi/notification_icon.png" />
    <resource-file src="resources/android/notification-icon/xxhdpi-notification-icon.png" target="app/src/main/res/drawable-xxhdpi/notification_icon.png" />
    <resource-file src="resources/android/notification-icon/xxxhdpi-notification-icon.png" target="app/src/main/res/drawable-xxxhdpi/notification_icon.png" />
    <config-file parent="/manifest/application" target="AndroidManifest.xml">
        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />
    </config-file>
    <preference name="loglevel" value="DEBUG" />
    <preference name="Fullscreen" value="false" />
    <preference name="Orientation" value="portrait" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="HideKeyboardFormAccessoryBar" value="true" />
    <preference name="MediaPlaybackRequiresUserAction" value="false" />
    <preference name="UIWebViewBounce" value="false" />
    <preference name="ShowSplashScreenSpinner" value="false" />
    <preference name="AutoHideSplashScreen" value="false" />
    <preference name="FadeSplashScreen" value="true" />
    <preference name="FadeSplashScreenDuration" value="1000" />
    <preference name="StatusBarBackgroundColor" value="#1f4b7b" />
</widget>
```

Regards
