### ISSUE TITLE
cmd --release build is failing after upgrading firebaseX plugin to 10.1.2-cli version for ios

### ISSUE THREAD

**Issue by bhargavas12** [dpa99c/cordova-plugin-firebasex#676]
Upgraded plugin to FirebaseX: 10.1.2-cli version and the xcode build with --release is succeded for ios but its failing when I build it through cmd line.

Not sure of the root cause and has been struck and no clue on how to resolve this.

Please help!!

**Plugin Info:**

cordova-ios: 5.1.1
firebaseX: 10.1.2-cli
cocoapods version: 1.10.1
xcode: 12.4

**error log:**
In file included from /Users/runner/work/1/s/platforms/ios/app/Plugins/cordova-plugin-firebasex/FirebasePlugin.m:1:
/Users/runner/work/1/s/platforms/ios/Workforce/Plugins/cordova-plugin-firebasex/FirebasePlugin.h:4:9: fatal error: module 'FirebaseFirestore' not found
@import FirebaseFirestore;
 ~~~~~~~^~~~~~~~~~~~~~~~~
1 error generated.


The following build commands failed:
	CompileC /Users/runner/Library/Developer/Xcode/DerivedData/app-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/app.build/Release-iphonesimulator/app.build/Objects-normal/x86_64/FirebasePlugin.o /Users/runner/work/1/s/platforms/ios/app/Plugins/cordova-plugin-firebasex/FirebasePlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios --release exited with exit code 65.

**Comment by harpster604** [comment]
@bhargavas12 how did you resolve this? I'm experiencing the same issue right now.
